/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_with_pooka;

import static app_with_pooka.KelimelerYonetimiForm.con;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kenan Savas
 */
public class KaraListeYonetimiForm extends javax.swing.JFrame {

    ResultSet rs;
    public static java.sql.Connection con;
    Statement statement;
    String sql;

    ArrayList<ArrayList<String>> allRecords=null;
    ArrayList<String> subRecords=null;

    /**
     * Creates new form KaraListeYonetimiForm
     */
    public KaraListeYonetimiForm() {
        initComponents();
        try{
            con = DriverManager.getConnection("jdbc:ucanaccess://db/akilli_eposta_db.mdb");
            con.setAutoCommit(false);
        }catch(Exception exp){
            exp.printStackTrace();
        }
        allRecords=getFieldsFromTable("[karaliste_ayarlar]", 6);
        
        if (allRecords!=null){
            String[] tableHeaderArray=new String[]{"karaliste_id","karaliste_hesapid","karaliste_filtreadi","karaliste_filtredegeri1","karaliste_filtredegeri2","karaliste_filtredegeri3"}; 
            String[][] tableRowArray=new String[allRecords.size()][]; 
            for(int i=0; i<allRecords.size(); i++){
                subRecords=allRecords.get(i);
                tableRowArray[i]=new String[]{                                   
                    subRecords.get(0),
                    subRecords.get(1),
                    subRecords.get(2),
                    subRecords.get(3),
                    subRecords.get(4),
                    subRecords.get(5)
                };
            }
            TableModel tableModel=new DefaultTableModel(tableRowArray,tableHeaderArray);
            jTable.setModel(tableModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablePropertyChange
        int tablePosition;
        tablePosition=jTable.getSelectedRow();
        System.out.println("tablePosition: "+tablePosition);
    }//GEN-LAST:event_jTablePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaraListeYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaraListeYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaraListeYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaraListeYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KaraListeYonetimiForm().setVisible(true);
            }
        });
    }

    /**
     * bir tabloya SELECT sorgusu ceker ve sonuclari ArrayList<ArrayList<String>>
     * yapısında geriye dondurur.
     * @param tableName veritabanindaki tablo ismi
     * @param totalFieldCount alan adedi,  kac tane alan getirilmesi gerektigini belirtir
     * @return ArrayList<ArrayList<String>> yapisinda geriye veriler doner veya bos ise null dondurulur.
     */
    public ArrayList<ArrayList<String>> getFieldsFromTable(String tableName, int totalFieldCount){
        ArrayList<ArrayList<String>> allRecords=new ArrayList<ArrayList<String>>();
        ArrayList<String> rowFields=null;
        try{
            sql = "SELECT * FROM "+tableName;
            statement = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            rs = statement.executeQuery(sql);				
            con.commit();
            statement.close();
            rs.first();
            if (rs.wasNull())
                return null;
            try{
                while(!rs.isAfterLast()){
                    rowFields=new ArrayList<String>();
                    for(int i=1; i<=totalFieldCount; i++){
                        rowFields.add(rs.getString(i));
                        //System.out.println("veritabani degeri: "+rs.getString(i));
                    }
                    allRecords.add(rowFields);
                    rs.next();
                }
            }catch(Exception exp){
                return null;
            }
        }catch(Exception exp){
            exp.printStackTrace();
        }
        //allRecords.remove(allRecords.size()-1);
        if (allRecords.size()==0)
            return null;
        else
            return allRecords;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
