/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_with_pooka;

/**
 *
 * @author Kenan Savas
 */
public class MainFormOfDBManagement extends javax.swing.JFrame {

    int accountID=-1;

    /**
     * Creates new form MainFormOfDBManagement
     */
    public MainFormOfDBManagement() {
        initComponents();
        accountID=1;
    }

    /**
     * Creates new form MainFormOfDBManagement
     */
    public MainFormOfDBManagement(int accountID) {
        initComponents();
        this.accountID=accountID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Kelimeler_Yonetimi = new javax.swing.JButton();
        jButton_Epostalar_Yonetimi = new javax.swing.JButton();
        jButton_Spam_Epostalar_Yonetimi = new javax.swing.JButton();
        jButton_Kara_Liste_Yonetimi = new javax.swing.JButton();
        jButton_Spam_Ayarlari_Yonetimi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Istatistikler_Yonetimi = new javax.swing.JButton();

        setTitle("AYARLAR VE VERİTABANI YÖNETİM EKRANI");

        jButton_Kelimeler_Yonetimi.setText("Kelimeler Yönetimi");
        jButton_Kelimeler_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Kelimeler_YonetimiActionPerformed(evt);
            }
        });

        jButton_Epostalar_Yonetimi.setText("E-Postalar Yönetimi");
        jButton_Epostalar_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Epostalar_YonetimiActionPerformed(evt);
            }
        });

        jButton_Spam_Epostalar_Yonetimi.setText("Spam E-Postalar Yönetimi");
        jButton_Spam_Epostalar_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Spam_Epostalar_YonetimiActionPerformed(evt);
            }
        });

        jButton_Kara_Liste_Yonetimi.setText("Kara Liste Yönetimi");
        jButton_Kara_Liste_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Kara_Liste_YonetimiActionPerformed(evt);
            }
        });

        jButton_Spam_Ayarlari_Yonetimi.setText("Spam Ayarları Yönetimi");
        jButton_Spam_Ayarlari_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Spam_Ayarlari_YonetimiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AYARLAR VE VERİTABANI YÖNETİM EKRANI");

        jButton_Istatistikler_Yonetimi.setText("İstatistikler Yönetimi");
        jButton_Istatistikler_Yonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Istatistikler_YonetimiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Spam_Ayarlari_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Kara_Liste_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Spam_Epostalar_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Epostalar_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Kelimeler_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Istatistikler_Yonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Kelimeler_Yonetimi)
                .addGap(18, 18, 18)
                .addComponent(jButton_Epostalar_Yonetimi)
                .addGap(18, 18, 18)
                .addComponent(jButton_Spam_Epostalar_Yonetimi)
                .addGap(18, 18, 18)
                .addComponent(jButton_Istatistikler_Yonetimi)
                .addGap(20, 20, 20)
                .addComponent(jButton_Kara_Liste_Yonetimi)
                .addGap(18, 18, 18)
                .addComponent(jButton_Spam_Ayarlari_Yonetimi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Kelimeler_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Kelimeler_YonetimiActionPerformed
       KelimelerYonetimiForm kelimelerYonetimiForm=new KelimelerYonetimiForm();
       kelimelerYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Kelimeler_YonetimiActionPerformed

    private void jButton_Epostalar_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Epostalar_YonetimiActionPerformed
       EpostalarYonetimiForm epostalarYonetimiForm=new EpostalarYonetimiForm();
       epostalarYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Epostalar_YonetimiActionPerformed

    private void jButton_Spam_Epostalar_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Spam_Epostalar_YonetimiActionPerformed
       SpamEpostalarYonetimiForm spamEpostalarYonetimiForm=new SpamEpostalarYonetimiForm();
       spamEpostalarYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Spam_Epostalar_YonetimiActionPerformed

    private void jButton_Istatistikler_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Istatistikler_YonetimiActionPerformed
       IstatistiklerYonetimiForm istatistiklerYonetimiForm=new IstatistiklerYonetimiForm(this.accountID);
       istatistiklerYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Istatistikler_YonetimiActionPerformed

    private void jButton_Kara_Liste_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Kara_Liste_YonetimiActionPerformed
       KaraListeYonetimiForm karaListeYonetimiForm=new KaraListeYonetimiForm();
       karaListeYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Kara_Liste_YonetimiActionPerformed

    private void jButton_Spam_Ayarlari_YonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Spam_Ayarlari_YonetimiActionPerformed
       SpamAyarlariYonetimiForm spamAyarlariYonetimiForm=new SpamAyarlariYonetimiForm();
       spamAyarlariYonetimiForm.setVisible(true);
    }//GEN-LAST:event_jButton_Spam_Ayarlari_YonetimiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormOfDBManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormOfDBManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormOfDBManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormOfDBManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormOfDBManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Epostalar_Yonetimi;
    private javax.swing.JButton jButton_Istatistikler_Yonetimi;
    private javax.swing.JButton jButton_Kara_Liste_Yonetimi;
    private javax.swing.JButton jButton_Kelimeler_Yonetimi;
    private javax.swing.JButton jButton_Spam_Ayarlari_Yonetimi;
    private javax.swing.JButton jButton_Spam_Epostalar_Yonetimi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
